import Head from 'next/head'
import Avatar from '../components/Avatar'
import {ViewGridIcon,MicrophoneIcon} from '@heroicons/react/solid'
import {SearchIcon} from '@heroicons/react/outline'
import Image from 'next/image'
import Footer from '../components/Footer'
import { useRef } from 'react'
import { useRouter } from 'next/router'




export default function Home() {

  const searchInputRef = useRef(null);
  const router = useRouter();

  const search = (e) =>{
    e.preventDefault();
    const term = searchInputRef.current.value;

    if(!term) return;

    router.push(`/search?term=${term}`)
}
  return (
    <div className='flex flex-col items-center justify-center h-screen'>
      <Head>
        <title>Google Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="http://assets.stickpng.com/images/588525cd6f293bbfae451a37.png" />
      </Head>

    
      {/* Header */}
      <header className="flex mt-20 sm:mt-0 w-full p-5 justify-between text-gray-700">
        {/* left */}
        <div className="flex space-x-4 items-center">
          <p className='link'>About</p>
          <p className='link'>store</p>
        </div>

          {/* right */}
          <div className="flex space-x-4 items-center">
          <p className='link'>Gmail</p>
          <p className='link'>Images</p>

          {/* Icon  */}
          <ViewGridIcon className='h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer' />

          {/* Avatar */}
          <Avatar url="https://tutorsheba.com/images/1578826938.jpg" />
          </div>
      </header>

      {/* body */}

       <form className='flex flex-col items-center mt-40 flex-grow w-4/5'>
         <Image src='https://digitalglue.agency/wp-content/uploads/2015/09/google.png' width={300} height={100} />

         <div className='flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border border-gray-200 px-5 py-3 items-center sm:max-w-xl lg:max-w-2xl'>
            <SearchIcon className='h-5 mr-3 text-gray-500' />
            <input ref={searchInputRef} placeholder='Search Google or type URL' type="text" className='flex-grow focus:outline-none' />
            <MicrophoneIcon className='h-5 mr-3 text-gray-500'/>
         </div>
         <div className='flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:space-y-0 sm:flex-row sm:space-x-4'>
           <button onClick={search} className='btn'>Google Search</button>
           <button onClick={search} className='btn'>I'm feeling Lucky</button>
         </div>
       </form>



      {/* Footer */}
      <Footer />

    </div>
  )
}
